### ISSUE TITLE
Request for the trained diffusion model

### ISSUE THREAD

**Issue by Denwey1** [tsinghua-fib-lab/LCSim#1]
Thank you very much for open-sourcing this work, it is a commendable work, could you please provide the trained diffusion model weights?

**Comment by lionel-me** [comment]
Thank you for your attention to this work, but unfortunately due to the relevant [regulations](https://waymo.com/open/terms/) of WOMD, we cannot provide the models trained on it, but can only open source the untrained model architecture.
