### ISSUE TITLE
mismatched shape of the agent 

### ISSUE THREAD

**Issue by Len-Li** [tsinghua-fib-lab/LCSim#2]
Hi, 

Thanks for open-sourcing the awesome project!

I encounter an issue when training the diffusion model. The shape is mismatched in [here](https://github.com/tsinghua-fib-lab/LCSim/blob/7e10045a1ecc268b8e8545ee156ec7b4c99a3afa/motion_diff/dataset/utils.py#L26).

```
assert (
            self.num_historical_steps + self.num_future_steps
            == data["agent"]["xyz"].shape[1]
        )
```

```    
Here is the dimension of the agent:
    
print(data["agent"]["xyz"].shape, self.num_historical_steps + self.num_future_steps)

torch.Size([50, 198, 3]) 91                                                                                                                          
torch.Size([70, 198, 3]) 91                                                                                                                          
torch.Size([129, 199, 3]) 91                                                                                                                         
torch.Size([26, 199, 3]) 91                                                                                                                          
torch.Size([44, 198, 3]) 91                                                                                                                          
torch.Size([41, 198, 3]) 91    
```

It seems like we should add a sliding window to crop the time dimension of input data in the dataloader?

Thanks!

**Comment by lionel-me** [comment]
It seems that you used the 20s scenarios of WOMD. As mentioned in the readme, our diffusion model is trained on the 9s scenarios of WOMD, which were selected from the 20s scenarios by Waymo company by adding a sliding window.

**Comment by Len-Li** [comment]
> It seems that you used the 20s scenarios of WOMD. As mentioned in the readme, our diffusion model is trained on the 9s scenarios of WOMD, which were selected from the 20s scenarios by Waymo company by adding a sliding window.

Thanks for your reply. I will add a sliding window to it.

**Comment by Len-Li** [comment]
by the way, how to make a visualization like this on your website? The animation is very cool.
![image](https://github.com/tsinghua-fib-lab/LCSim/assets/40287745/d1bcf4e5-c4e7-4068-b3c2-03cae2ce6b4b)
