### ISSUE TITLE
Request for the pca_path

### ISSUE THREAD

**Issue by dicheny** [tsinghua-fib-lab/LCSim#3]
Hi!
Thank you very much for open-sourcing this work! It seems that pca_path is necessary for training diffusion model 

        if pca_path is not None:
            self.pca = PCA(pickle.load(open(pca_path, "rb")))

        # post pca

        if not self.target == "pca":
            a_center_traj = self.pca.forward(
                self.pca.forward(a_center_traj.reshape(a_center_traj.shape[0], -1)),
                inverse=True
            ).reshape(a_center_traj.shape)

but I don't know how to get it. Could you please provide it?

**Comment by lionel-me** [comment]
[Here](https://github.com/tsinghua-fib-lab/LCSim/tree/main/motion_diff/scripts) in the scripts, we provide tools for generating pca parameters and an example parameter generated from part of training set of WOMD.
