### ISSUE TITLE
Train from scratch

### ISSUE THREAD

**Issue by efyphil** [tsinghua-fib-lab/LCSim#5]
I tried training a diffusion network from scratch but ran into this problem 
FileNotFoundError: Checkpoint file not found: None

**Comment by efyphil** [comment]
<img width="1542" alt="Screenshot 2024-07-22 at 18 18 16" src="https://github.com/user-attachments/assets/f1f08d73-f409-4d5c-b5ff-9fab84616f18">
I'm also having trouble saving data to the h5 like file, perhaps these are related errors

**Comment by lionel-me** [comment]
It seems that there are some mistakes in the config file, we have updated it, try again.
