### ISSUE TITLE
A question about way_open_dataset 1.0.1 setup

### ISSUE THREAD

**Issue by StudentWwg** [tsinghua-fib-lab/LCSim#6]
Thanks for releasing the code of LCSim project. However, I encountered some problems about environment setup. Specifically, I create a conda environment according to your guidance in readme, which python version is 3.10. The issue occurs when I install waymo_open_data 1.0.1 using pip command.

> ERROR: Could not find a version that satisfies the requirement waymo_open_dataset==1.0.1 (from versions: none)
ERROR: No matching distribution found for waymo_open_dataset==1.0.1

I have searched some similar questions, but no one is matched. If there is any waymo_open_set version corresponding to python 3.10?

**Comment by lionel-me** [comment]
See if [this](https://github.com/tsinghua-fib-lab/LCSim/issues/4) closed issue can help you, it seems that there is something wrong with the generated requirements.txt, we will fix it later.
